name: Build and Deploy
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest # The first job utilizes windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install # The project is built using npm and placed in the 'build' folder.
        run: |
          npm install
          npm run build

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: dist/apps/portfolio
